export interface Subscription {
  id: number;
  amount: number;
  cost: number;
  title: string;
  photo: string;
  primary_color: string;
  footer_color: string;
  created_at: string;
  updated_at: string;
  deleted_at: string;
}

export interface VerifySubscriptionModel {
  duration?: string;
  coins_purchased?: number;
  amount_paid?: number;
  transaction_reference: string;
  payment_channel: "mobile";
  device?: string;
}

export interface BankPaymentModel {
  amount: number;
  email_address: string;
  account_number: string;
  bank_code: string;
  birthday: string;
}

export interface Bank {
  name: string;
  slug: string;
  code: string;
  longcode: string;
  gateway: string;
  pay_with_bank: boolean;
  active: boolean;
  is_deleted: string;
  country: string;
  currency: string;
  type: string;
  id: number;
  createdAt: string;
  updatedAt: string;

}

// Generated by https://quicktype.io

export interface PaystackResponse {
  status: boolean;
  message: string;
  data: Data;
}

export interface Data {
  reference: string;
  status: string;
  display_text: string;
  ussd_code?: string;
}
